version: '3'

services:
    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel
        ports:
            - 80:80
        volumes:
            - .:/var/www/html
